build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  LongMethod:
    threshold: 120
    ignoreAnnotated: ['Composable']
  LargeClass:
    threshold: 600
  ComplexCondition:
    threshold: 6
  CyclomaticComplexMethod:
    threshold: 20
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    thresholdInFiles: 40
    thresholdInClasses: 30
    thresholdInInterfaces: 30
    thresholdInObjects: 30
    thresholdInEnums: 30
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
    ignoreDefaultParameters: true
    ignoreDataClasses: true

naming:
  FunctionNaming:
    functionPattern: '^[a-zA-Z][a-zA-Z0-9]*$'
    ignoreAnnotated: ['Composable', 'Test']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    packagePattern: '^[a-z]+(\.[a-z][A-Za-z0-9]*)*$'

style:
  ReturnCount:
    max: 5
  MaxLineLength:
    maxLineLength: 180
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected)'
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
